server.port=8080

# Enable discovery-based routing
spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true


# Auth Service
spring.cloud.gateway.server.webflux.routes[0].id=auth-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://Hotel-AuthService
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/auth/**
