server.port=8083

spring.datasource.url=jdbc:postgresql://localhost:5432/booking_db
spring.datasource.username=postgres
spring.datasource.password=1729

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=false
spring.datasource.driver-class-name=org.postgresql.Driver

eureka.instance.prefer-ip-address=true

